"""
AYUSH / Dashavidha questionnaire definition for the MediMinds clinical prototype.

SOURCE OF TRUTH:
    AYUSH_Dashavidha_Patient_Friendly_Questionnaire - Copy.docx

This module defines questionnaire metadata only. It does not perform diagnosis,
Ayurvedic scoring/mapping, treatment recommendations, red-flag detection,
database access, API routing, or AI/LLM processing.
"""

from typing import Any, Dict, List, Optional

VALID_ANSWER_TYPES = {
    "single_choice", "multiple_choice", "free_text", "number", "date",
}

VALID_SOURCES = {
    "self_reported", "measured", "clinician_entered",
}

DASHAVIDHA_QUESTIONNAIRE: Dict[str, Dict[str, Any]] = {
    'prakriti': {   'category_id': 'prakriti',
    'category_name': 'Prakriti',
    'description': "The person's constitutional or baseline body–mind tendency, traditionally described through the "
                   'relative predominance of Vata, Pitta and Kapha characteristics. It is intended to describe '
                   'relatively stable individual traits rather than a current illness.',
    'information_focus': 'Usual body and behavioral characteristics',
    'questions': [   {   'question_id': 'prakriti_body_build_01',
                         'category': 'prakriti',
                         'question_text': 'How would you describe your usual body build?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'lean', 'label': 'Lean'},
                                        {'value': 'medium', 'label': 'Medium'},
                                        {'value': 'broad_or_solid', 'label': 'Broad or solid'},
                                        {'value': 'not_sure', 'label': 'Not sure'}]},
                     {   'question_id': 'prakriti_natural_weight_tendency_01',
                         'category': 'prakriti',
                         'question_text': 'When your routine and diet are fairly normal, does your weight usually stay '
                                          'stable, tend to be low, or tend to increase easily?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'low', 'label': 'Low'},
                                        {'value': 'stable', 'label': 'Stable'},
                                        {'value': 'increases_easily', 'label': 'Increases easily'},
                                        {'value': 'unsure', 'label': 'Unsure'}]},
                     {   'question_id': 'prakriti_appetite_tendency_01',
                         'category': 'prakriti',
                         'question_text': 'How would you describe your usual appetite when you are well?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'irregular', 'label': 'Irregular'},
                                        {'value': 'strong', 'label': 'Strong'},
                                        {'value': 'moderate_steady', 'label': 'Moderate-steady'},
                                        {'value': 'variable', 'label': 'Variable'}]},
                     {   'question_id': 'prakriti_digestion_tendency_01',
                         'category': 'prakriti',
                         'question_text': 'When you are generally well, how does your digestion usually feel after '
                                          'meals?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'often_irregular', 'label': 'Often irregular'},
                                        {'value': 'often_fast_or_strong', 'label': 'Often fast or strong'},
                                        {'value': 'usually_slow_or_heavy', 'label': 'Usually slow or heavy'},
                                        {'value': 'usually_comfortable', 'label': 'Usually comfortable'},
                                        {'value': 'unsure', 'label': 'Unsure'}]},
                     {   'question_id': 'prakriti_sleep_pattern_01',
                         'category': 'prakriti',
                         'question_text': 'When you are well, how is your usual sleep?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'light_easily_disturbed', 'label': 'Light/easily disturbed'},
                                        {'value': 'moderate', 'label': 'Moderate'},
                                        {'value': 'deep_long', 'label': 'Deep/long'},
                                        {'value': 'variable', 'label': 'Variable'}]},
                     {   'question_id': 'prakriti_skin_01',
                         'category': 'prakriti',
                         'question_text': 'How is your skin usually?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'dry', 'label': 'Dry'},
                                        {'value': 'warm_or_sensitive', 'label': 'Warm or sensitive'},
                                        {'value': 'soft_oily', 'label': 'Soft/oily'},
                                        {'value': 'normal_or_mixed', 'label': 'Normal or mixed'},
                                        {'value': 'unsure', 'label': 'Unsure'}]},
                     {   'question_id': 'prakriti_hair_01',
                         'category': 'prakriti',
                         'question_text': 'How is your hair usually?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'dry_thin', 'label': 'Dry/thin'},
                                        {'value': 'fine_or_soft', 'label': 'Fine or soft'},
                                        {'value': 'thick_oily', 'label': 'Thick/oily'},
                                        {'value': 'mixed', 'label': 'Mixed'},
                                        {'value': 'unsure', 'label': 'Unsure'}]},
                     {   'question_id': 'prakriti_temperature_preference_01',
                         'category': 'prakriti',
                         'question_text': 'Do you usually feel more comfortable in cool conditions, warm conditions, '
                                          'or neither?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'prefer_warmth', 'label': 'Prefer warmth'},
                                        {'value': 'prefer_coolness', 'label': 'Prefer coolness'},
                                        {'value': 'neither', 'label': 'Neither'}]},
                     {   'question_id': 'prakriti_activity_energy_01',
                         'category': 'prakriti',
                         'question_text': 'How would you describe your usual energy and activity level?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'quick_variable', 'label': 'Quick/variable'},
                                        {'value': 'high_active', 'label': 'High/active'},
                                        {'value': 'steady_slow', 'label': 'Steady/slow'},
                                        {'value': 'mixed', 'label': 'Mixed'}]},
                     {   'question_id': 'prakriti_personality_behavior_tendency_01',
                         'category': 'prakriti',
                         'question_text': 'Which description is closest to how you usually behave when you are well?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'quick_changing_active', 'label': 'Quick-changing/active'},
                                        {'value': 'focused_intense', 'label': 'Focused/intense'},
                                        {'value': 'calm_steady', 'label': 'Calm/steady'},
                                        {'value': 'mixed', 'label': 'Mixed'}]}]},
    'vikriti': {   'category_id': 'vikriti',
    'category_name': 'Vikriti',
    'description': "The person's current state or deviation from their usual baseline, including present symptoms, "
                   'changes in appetite, sleep, digestion, energy, bowel habits, and other current complaints.',
    'information_focus': "Current symptoms and changes from the person's normal state",
    'questions': [   {   'question_id': 'vikriti_main_current_problem_01',
                         'category': 'vikriti',
                         'question_text': 'What is the main health problem you are experiencing right now?',
                         'required': None,
                         'timeframe': 'current',
                         'source': 'self_reported',
                         'answer_type': 'free_text'},
                     {   'question_id': 'vikriti_change_from_normal_01',
                         'category': 'vikriti',
                         'question_text': 'What has changed from your usual health or routine?',
                         'required': None,
                         'timeframe': 'current',
                         'source': 'self_reported',
                         'answer_type': 'free_text'},
                     {   'question_id': 'vikriti_current_appetite_01',
                         'category': 'vikriti',
                         'question_text': 'Compared with your usual appetite, how is your appetite now?',
                         'required': None,
                         'timeframe': 'current',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'lower', 'label': 'Lower'},
                                        {'value': 'higher', 'label': 'Higher'},
                                        {'value': 'about_the_same', 'label': 'About the same'},
                                        {'value': 'variable', 'label': 'Variable'}]},
                     {   'question_id': 'vikriti_current_digestion_01',
                         'category': 'vikriti',
                         'question_text': 'How has your digestion been recently?',
                         'required': None,
                         'timeframe': 'current',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'normal', 'label': 'Normal'},
                                        {'value': 'indigestion', 'label': 'Indigestion'},
                                        {'value': 'bloating_gas', 'label': 'Bloating/gas'},
                                        {'value': 'burning_acidity', 'label': 'Burning/acidity'},
                                        {'value': 'heavy_slow', 'label': 'Heavy/slow'},
                                        {'value': 'other', 'label': 'Other'}]},
                     {   'question_id': 'vikriti_bowel_habit_01',
                         'category': 'vikriti',
                         'question_text': 'Have your bowel movements changed recently?',
                         'required': None,
                         'timeframe': 'current',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'no', 'label': 'No'},
                                        {'value': 'constipation', 'label': 'Constipation'},
                                        {'value': 'loose_stools', 'label': 'Loose stools'},
                                        {'value': 'more_frequent', 'label': 'More frequent'},
                                        {'value': 'less_frequent', 'label': 'Less frequent'},
                                        {'value': 'other', 'label': 'Other'}]},
                     {   'question_id': 'vikriti_sleep_change_01',
                         'category': 'vikriti',
                         'question_text': 'Has your sleep changed recently?',
                         'required': None,
                         'timeframe': 'current',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'no', 'label': 'No'},
                                        {'value': 'difficulty_falling_asleep', 'label': 'Difficulty falling asleep'},
                                        {'value': 'frequent_waking', 'label': 'Frequent waking'},
                                        {'value': 'sleeping_more', 'label': 'Sleeping more'},
                                        {'value': 'other', 'label': 'Other'}]},
                     {   'question_id': 'vikriti_energy_change_01',
                         'category': 'vikriti',
                         'question_text': 'How has your energy been recently compared with normal?',
                         'required': None,
                         'timeframe': 'current',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'lower', 'label': 'Lower'},
                                        {'value': 'higher_restless', 'label': 'Higher/restless'},
                                        {'value': 'about_the_same', 'label': 'About the same'},
                                        {'value': 'variable', 'label': 'Variable'}]},
                     {   'question_id': 'vikriti_symptom_duration_01',
                         'category': 'vikriti',
                         'question_text': 'How long have these changes or symptoms been present?',
                         'required': None,
                         'timeframe': 'current',
                         'source': 'self_reported',
                         'answer_type': 'free_text'}]},
    'sara': {   'category_id': 'sara',
    'category_name': 'Sara',
    'description': "The assessment of the quality or strength of the body's tissues and overall tissue health, "
                   'traditionally considered across seven tissue categories. For a patient-facing prototype, this '
                   'should be represented through observable/general health characteristics rather than asking the '
                   'patient to name tissue categories.',
    'information_focus': 'General tissue quality and overall physical health',
    'questions': [   {   'question_id': 'sara_overall_physical_health_01',
                         'category': 'sara',
                         'question_text': 'How would you describe your overall physical strength and health when you '
                                          'are well?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'poor', 'label': 'Poor'},
                                        {'value': 'fair', 'label': 'Fair'},
                                        {'value': 'good', 'label': 'Good'},
                                        {'value': 'very_good', 'label': 'Very good'}]},
                     {   'question_id': 'sara_muscle_quality_01',
                         'category': 'sara',
                         'question_text': 'How would you describe your usual muscle strength and development?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'low', 'label': 'Low'},
                                        {'value': 'average', 'label': 'Average'},
                                        {'value': 'good', 'label': 'Good'},
                                        {'value': 'very_good', 'label': 'Very good'},
                                        {'value': 'unsure', 'label': 'Unsure'}]},
                     {   'question_id': 'sara_skin_complexion_01',
                         'category': 'sara',
                         'question_text': 'How would you describe your usual skin health?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'poor', 'label': 'Poor'},
                                        {'value': 'average', 'label': 'Average'},
                                        {'value': 'good', 'label': 'Good'},
                                        {'value': 'very_good', 'label': 'Very good'}]},
                     {   'question_id': 'sara_hair_nails_01',
                         'category': 'sara',
                         'question_text': 'How would you describe the usual health of your hair and nails?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'poor', 'label': 'Poor'},
                                        {'value': 'average', 'label': 'Average'},
                                        {'value': 'good', 'label': 'Good'},
                                        {'value': 'very_good', 'label': 'Very good'},
                                        {'value': 'unsure', 'label': 'Unsure'}]},
                     {   'question_id': 'sara_recovery_01',
                         'category': 'sara',
                         'question_text': 'After illness, injury or significant exertion, how well do you usually '
                                          'recover?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'slowly', 'label': 'Slowly'},
                                        {'value': 'moderately', 'label': 'Moderately'},
                                        {'value': 'quickly', 'label': 'Quickly'},
                                        {'value': 'unsure', 'label': 'Unsure'}]},
                     {   'question_id': 'sara_general_vitality_01',
                         'category': 'sara',
                         'question_text': 'How would you rate your usual overall vitality?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'low', 'label': 'Low'},
                                        {'value': 'moderate', 'label': 'Moderate'},
                                        {'value': 'high', 'label': 'High'},
                                        {'value': 'very_high', 'label': 'Very high'}]}]},
    'samhanana': {   'category_id': 'samhanana',
    'category_name': 'Samhanana',
    'description': 'The compactness, proportion and structural build of the body, especially the relationship and '
                   'robustness of bones, joints, muscles and body structure.',
    'information_focus': 'Body structure, compactness and musculoskeletal build',
    'questions': [   {   'question_id': 'samhanana_body_frame_01',
                         'category': 'samhanana',
                         'question_text': 'How would you describe your natural body frame?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'small', 'label': 'Small'},
                                        {'value': 'medium', 'label': 'Medium'},
                                        {'value': 'large', 'label': 'Large'}]},
                     {   'question_id': 'samhanana_bone_joint_build_01',
                         'category': 'samhanana',
                         'question_text': 'How would you describe your bones and joints?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'fine_small', 'label': 'Fine/small'},
                                        {'value': 'medium', 'label': 'Medium'},
                                        {'value': 'large_strong', 'label': 'Large/strong'},
                                        {'value': 'unsure', 'label': 'Unsure'}]},
                     {   'question_id': 'samhanana_muscle_structural_build_01',
                         'category': 'samhanana',
                         'question_text': 'How would you describe your usual muscle and body structure?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'light', 'label': 'Light'},
                                        {'value': 'moderate', 'label': 'Moderate'},
                                        {'value': 'well_developed', 'label': 'Well-developed'},
                                        {'value': 'very_robust', 'label': 'Very robust'}]},
                     {   'question_id': 'samhanana_joint_stability_01',
                         'category': 'samhanana',
                         'question_text': 'Do your joints generally feel stable and strong?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'yes', 'label': 'Yes'},
                                        {'value': 'sometimes', 'label': 'Sometimes'},
                                        {'value': 'no', 'label': 'No'},
                                        {'value': 'unsure', 'label': 'Unsure'}]},
                     {   'question_id': 'samhanana_physical_robustness_01',
                         'category': 'samhanana',
                         'question_text': 'How physically robust do you consider yourself compared with people of a '
                                          'similar age?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'less_robust', 'label': 'Less robust'},
                                        {'value': 'similar', 'label': 'Similar'},
                                        {'value': 'more_robust', 'label': 'More robust'},
                                        {'value': 'unsure', 'label': 'Unsure'}]}]},
    'pramana': {   'category_id': 'pramana',
    'category_name': 'Pramana',
    'description': 'Assessment of body measurements and proportions. In a modern prototype, this can be represented by '
                   'objective measurements such as height, weight and, where appropriate, waist circumference/BMI, '
                   'while avoiding unsupported traditional calculations.',
    'information_focus': 'Objective body measurements and proportions',
    'questions': [   {   'question_id': 'pramana_age_01',
                         'category': 'pramana',
                         'question_text': 'What is your age?',
                         'required': None,
                         'timeframe': 'current_measurement',
                         'source': 'self_reported',
                         'answer_type': 'number',
                         'unit': 'years'},
                     {   'question_id': 'pramana_height_01',
                         'category': 'pramana',
                         'question_text': 'What is your height?',
                         'required': None,
                         'timeframe': 'current_measurement',
                         'source': 'measured',
                         'answer_type': 'number',
                         'unit': 'cm'},
                     {   'question_id': 'pramana_weight_01',
                         'category': 'pramana',
                         'question_text': 'What is your current weight?',
                         'required': None,
                         'timeframe': 'current_measurement',
                         'source': 'measured',
                         'answer_type': 'number',
                         'unit': 'kg'},
                     {   'question_id': 'pramana_waist_circumference_01',
                         'category': 'pramana',
                         'question_text': 'If available, what is your waist circumference?',
                         'required': None,
                         'timeframe': 'current_measurement',
                         'source': 'measured',
                         'answer_type': 'number',
                         'unit': 'cm',
                         'allow_not_available': True},
                     {   'question_id': 'pramana_other_measured_values_01',
                         'category': 'pramana',
                         'question_text': 'Are there any recent body measurements that your clinician wants to record?',
                         'required': None,
                         'timeframe': 'current_measurement',
                         'source': 'clinician_entered',
                         'answer_type': 'free_text'}]},
    'satmya': {   'category_id': 'satmya',
    'category_name': 'Satmya',
    'description': "The person's habituation and compatibility with foods, routines, climate, lifestyle and other "
                   'exposures—what their body generally tolerates well because of regular use or adaptation.',
    'information_focus': 'What the person is accustomed to and tolerates well',
    'questions': [   {   'question_id': 'satmya_usual_diet_01',
                         'category': 'satmya',
                         'question_text': 'What kind of food do you normally eat most often?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'free_text'},
                     {   'question_id': 'satmya_food_tolerance_01',
                         'category': 'satmya',
                         'question_text': 'Are there foods that you regularly eat without discomfort or problems?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'free_text'},
                     {   'question_id': 'satmya_food_intolerance_01',
                         'category': 'satmya',
                         'question_text': 'Are there foods that commonly cause discomfort, bloating, loose stools, '
                                          'acidity, rash, or another reaction?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'free_text'},
                     {   'question_id': 'satmya_routine_01',
                         'category': 'satmya',
                         'question_text': 'Which daily routines are you accustomed to?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'regular_meals', 'label': 'Regular meals'},
                                        {'value': 'regular_sleep', 'label': 'Regular sleep'},
                                        {'value': 'exercise', 'label': 'Exercise'},
                                        {'value': 'other', 'label': 'Other'}]},
                     {   'question_id': 'satmya_climate_tolerance_01',
                         'category': 'satmya',
                         'question_text': 'Which environment do you generally tolerate better?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'hot', 'label': 'Hot'},
                                        {'value': 'cold', 'label': 'Cold'},
                                        {'value': 'both_similarly', 'label': 'Both similarly'},
                                        {'value': 'unsure', 'label': 'Unsure'}]},
                     {   'question_id': 'satmya_lifestyle_adaptation_01',
                         'category': 'satmya',
                         'question_text': 'Are there regular activities or habits that your body is well accustomed '
                                          'to?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'free_text'}]},
    'satva': {   'category_id': 'satva',
    'category_name': 'Satva',
    'description': 'Assessment of mental strength/resilience, coping capacity, confidence, emotional stability and '
                   'ability to handle stress or difficult situations.',
    'information_focus': 'Mental resilience, coping and emotional stability',
    'questions': [   {   'question_id': 'satva_stress_response_01',
                         'category': 'satva',
                         'question_text': 'When you face a stressful situation, how do you usually respond?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'become_easily_overwhelmed', 'label': 'Become easily overwhelmed'},
                                        {'value': 'usually_cope', 'label': 'Usually cope'},
                                        {'value': 'remain_calm_and_focused', 'label': 'Remain calm and focused'},
                                        {'value': 'variable', 'label': 'Variable'}]},
                     {   'question_id': 'satva_coping_ability_01',
                         'category': 'satva',
                         'question_text': 'How well do you usually manage difficult situations?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'with_difficulty', 'label': 'With difficulty'},
                                        {'value': 'moderately_well', 'label': 'Moderately well'},
                                        {'value': 'very_well', 'label': 'Very well'}]},
                     {   'question_id': 'satva_confidence_01',
                         'category': 'satva',
                         'question_text': 'How confident do you generally feel when dealing with challenges?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'low', 'label': 'Low'},
                                        {'value': 'moderate', 'label': 'Moderate'},
                                        {'value': 'high', 'label': 'High'}]},
                     {   'question_id': 'satva_emotional_recovery_01',
                         'category': 'satva',
                         'question_text': 'After something upsetting happens, how quickly do you usually feel back to '
                                          'normal?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'slowly', 'label': 'Slowly'},
                                        {'value': 'moderately', 'label': 'Moderately'},
                                        {'value': 'quickly', 'label': 'Quickly'}]},
                     {   'question_id': 'satva_concentration_01',
                         'category': 'satva',
                         'question_text': 'How well can you usually stay focused on a task?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'poor', 'label': 'Poor'},
                                        {'value': 'fair', 'label': 'Fair'},
                                        {'value': 'good', 'label': 'Good'},
                                        {'value': 'very_good', 'label': 'Very good'}]},
                     {   'question_id': 'satva_support_01',
                         'category': 'satva',
                         'question_text': 'When you are under stress, do you usually have someone you can rely on?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'yes', 'label': 'Yes'},
                                        {'value': 'sometimes', 'label': 'Sometimes'},
                                        {'value': 'no', 'label': 'No'},
                                        {'value': 'prefer_not_to_say', 'label': 'Prefer not to say'}]}]},
    'ahara_shakti': {   'category_id': 'ahara_shakti',
    'category_name': 'Ahara Shakti',
    'description': 'Assessment of digestive/food-handling capacity: appetite, ability to consume food, digestion after '
                   "meals, meal tolerance and the person's usual eating capacity.",
    'information_focus': 'Appetite, meal capacity and digestion',
    'questions': [   {   'question_id': 'ahara_shakti_usual_hunger_01',
                         'category': 'ahara_shakti',
                         'question_text': 'How often do you usually feel hungry during the day?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'rarely', 'label': 'Rarely'},
                                        {'value': '1_2_times', 'label': '1–2 times'},
                                        {'value': '3_times', 'label': '3 times'},
                                        {'value': 'frequently', 'label': 'Frequently'}]},
                     {   'question_id': 'ahara_shakti_meal_capacity_01',
                         'category': 'ahara_shakti',
                         'question_text': 'How much food can you usually eat comfortably at one meal?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'small_amount', 'label': 'Small amount'},
                                        {'value': 'moderate_amount', 'label': 'Moderate amount'},
                                        {'value': 'large_amount', 'label': 'Large amount'},
                                        {'value': 'variable', 'label': 'Variable'}]},
                     {   'question_id': 'ahara_shakti_meal_tolerance_01',
                         'category': 'ahara_shakti',
                         'question_text': 'After a normal meal, how do you usually feel?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'comfortable', 'label': 'Comfortable'},
                                        {'value': 'heavy_or_sleepy', 'label': 'Heavy or sleepy'},
                                        {'value': 'burning_acidity', 'label': 'Burning/acidity'},
                                        {'value': 'bloating_gas', 'label': 'Bloating/gas'},
                                        {'value': 'other', 'label': 'Other'}]},
                     {   'question_id': 'ahara_shakti_hunger_regularity_01',
                         'category': 'ahara_shakti',
                         'question_text': 'Does your hunger come at fairly regular times?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'yes', 'label': 'Yes'},
                                        {'value': 'no', 'label': 'No'},
                                        {'value': 'variable', 'label': 'Variable'}]},
                     {   'question_id': 'ahara_shakti_digestion_after_meals_01',
                         'category': 'ahara_shakti',
                         'question_text': 'How long does it usually take before you feel comfortable and ready for '
                                          'your next meal?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'short', 'label': 'Short'},
                                        {'value': 'moderate', 'label': 'Moderate'},
                                        {'value': 'long', 'label': 'Long'},
                                        {'value': 'variable', 'label': 'Variable'}]},
                     {   'question_id': 'ahara_shakti_appetite_change_01',
                         'category': 'ahara_shakti',
                         'question_text': 'Has your ability to eat or your appetite changed recently?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'no', 'label': 'No'},
                                        {'value': 'decreased', 'label': 'Decreased'},
                                        {'value': 'increased', 'label': 'Increased'},
                                        {'value': 'variable', 'label': 'Variable'}]}]},
    'vyayama_shakti': {   'category_id': 'vyayama_shakti',
    'category_name': 'Vyayama Shakti',
    'description': 'Assessment of exercise capacity or physical endurance—how much physical activity the person can '
                   'perform comfortably and how they recover from exertion.',
    'information_focus': 'Physical activity capacity and endurance',
    'questions': [   {   'question_id': 'vyayama_shakti_usual_activity_01',
                         'category': 'vyayama_shakti',
                         'question_text': 'How physically active are you on a normal day?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'mostly_sedentary', 'label': 'Mostly sedentary'},
                                        {'value': 'lightly_active', 'label': 'Lightly active'},
                                        {'value': 'moderately_active', 'label': 'Moderately active'},
                                        {'value': 'very_active', 'label': 'Very active'}]},
                     {   'question_id': 'vyayama_shakti_exercise_tolerance_01',
                         'category': 'vyayama_shakti',
                         'question_text': 'How much continuous physical activity can you usually do comfortably?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'less_than_10_min', 'label': 'Less than 10 min'},
                                        {'value': '10_30_min', 'label': '10–30 min'},
                                        {'value': '30_60_min', 'label': '30–60 min'},
                                        {'value': 'more_than_60_min', 'label': 'More than 60 min'}]},
                     {   'question_id': 'vyayama_shakti_breathlessness_fatigue_01',
                         'category': 'vyayama_shakti',
                         'question_text': 'During usual activity, do you become unusually tired or short of breath?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'no', 'label': 'No'},
                                        {'value': 'sometimes', 'label': 'Sometimes'},
                                        {'value': 'often', 'label': 'Often'},
                                        {'value': 'depends_on_activity', 'label': 'Depends on activity'}]},
                     {   'question_id': 'vyayama_shakti_recovery_01',
                         'category': 'vyayama_shakti',
                         'question_text': 'After exercise, how quickly do you usually return to your normal energy '
                                          'level?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'slowly', 'label': 'Slowly'},
                                        {'value': 'moderately', 'label': 'Moderately'},
                                        {'value': 'quickly', 'label': 'Quickly'}]},
                     {   'question_id': 'vyayama_shakti_strength_endurance_01',
                         'category': 'vyayama_shakti',
                         'question_text': 'Which best describes your physical capacity?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'single_choice',
                         'options': [   {'value': 'low', 'label': 'Low'},
                                        {'value': 'moderate', 'label': 'Moderate'},
                                        {'value': 'good', 'label': 'Good'},
                                        {'value': 'high', 'label': 'High'}]},
                     {   'question_id': 'vyayama_shakti_usual_exercise_01',
                         'category': 'vyayama_shakti',
                         'question_text': 'What types of exercise or physical activity do you normally do?',
                         'required': None,
                         'timeframe': 'usual_baseline',
                         'source': 'self_reported',
                         'answer_type': 'free_text'}]},
    'vaya': {   'category_id': 'vaya',
    'category_name': 'Vaya',
    'description': "The person's age and life stage. In a questionnaire this should primarily be captured through date "
                   'of birth/age, with life-stage interpretation handled by the system rather than guessed by the '
                   'patient.',
    'information_focus': 'Age and life stage',
    'questions': [   {   'question_id': 'vaya_age_01',
                         'category': 'vaya',
                         'question_text': 'What is your age?',
                         'required': None,
                         'timeframe': 'current',
                         'source': 'self_reported',
                         'answer_type': 'number',
                         'unit': 'years'},
                     {   'question_id': 'vaya_date_of_birth_01',
                         'category': 'vaya',
                         'question_text': 'What is your date of birth?',
                         'required': None,
                         'timeframe': 'current',
                         'source': 'self_reported',
                         'answer_type': 'date'},
                     {   'question_id': 'vaya_life_stage_context_01',
                         'category': 'vaya',
                         'question_text': "Are there any age-related life-stage factors that are important for today's "
                                          'assessment?',
                         'required': None,
                         'timeframe': 'current',
                         'source': 'clinician_entered',
                         'answer_type': 'free_text'}]}
}


def get_all_questions() -> List[Dict[str, Any]]:
    """Return all questionnaire questions in category order."""
    return [
        question
        for category in DASHAVIDHA_QUESTIONNAIRE.values()
        for question in category["questions"]
    ]


def get_category(category_id: str) -> Optional[Dict[str, Any]]:
    """Return one category by stable category ID, or None if not found."""
    return DASHAVIDHA_QUESTIONNAIRE.get(category_id)


def get_questions_by_category(category_id: str) -> List[Dict[str, Any]]:
    """Return questions for a category, or an empty list if not found."""
    category = get_category(category_id)
    return list(category["questions"]) if category else []


def get_question(question_id: str) -> Optional[Dict[str, Any]]:
    """Return one question by stable question ID, or None if not found."""
    for question in get_all_questions():
        if question["question_id"] == question_id:
            return question
    return None


def get_questionnaire_payload() -> Dict[str, Any]:
    """Return the questionnaire in an API-friendly, JSON-serializable shape."""
    return {"categories": list(DASHAVIDHA_QUESTIONNAIRE.values())}


def validate_questionnaire() -> List[str]:
    """Return structural validation errors; an empty list means valid."""
    errors: List[str] = []
    seen_ids = set()

    if len(DASHAVIDHA_QUESTIONNAIRE) != 10:
        errors.append("Expected exactly 10 categories.")

    for category_key, category in DASHAVIDHA_QUESTIONNAIRE.items():
        if category.get("category_id") != category_key:
            errors.append(f"Category key '{category_key}' does not match category_id.")

        if not category.get("category_name"):
            errors.append(f"Category '{category_key}' has no category_name.")

        questions = category.get("questions")
        if not isinstance(questions, list):
            errors.append(f"Category '{category_key}' has no valid questions list.")
            continue

        for question in questions:
            qid = question.get("question_id")

            if not qid:
                errors.append(f"Category '{category_key}' has a question without question_id.")
            elif qid in seen_ids:
                errors.append(f"Duplicate question_id: {qid}")
            else:
                seen_ids.add(qid)

            for field in ("category", "question_text", "answer_type"):
                if not question.get(field):
                    errors.append(f"Question '{qid}' is missing '{field}'.")

            if question.get("category") != category_key:
                errors.append(f"Question '{qid}' has the wrong category.")

            if question.get("answer_type") not in VALID_ANSWER_TYPES:
                errors.append(
                    f"Question '{qid}' has unsupported answer_type "
                    f"'{question.get('answer_type')}'."
                )

            if question.get("source") not in VALID_SOURCES:
                errors.append(
                    f"Question '{qid}' has invalid source '{question.get('source')}'."
                )

            if not question.get("timeframe"):
                errors.append(f"Question '{qid}' has no timeframe.")

            if question.get("answer_type") == "single_choice":
                options = question.get("options")
                if not isinstance(options, list) or not options:
                    errors.append(f"Choice question '{qid}' has no options.")
                else:
                    values = []
                    for option in options:
                        if not option.get("value") or not option.get("label"):
                            errors.append(f"Question '{qid}' has an option without value/label.")
                        values.append(option.get("value"))
                    if len(values) != len(set(values)):
                        errors.append(f"Question '{qid}' has duplicate option values.")

    return errors


if __name__ == "__main__":
    validation_errors = validate_questionnaire()
    if validation_errors:
        raise SystemExit("\n".join(validation_errors))
    print(
        f"Valid AYUSH questionnaire: {len(DASHAVIDHA_QUESTIONNAIRE)} categories, "
        f"{len(get_all_questions())} questions."
    )